name: Deploy Flutter Web to GitHub Pages

on:
 push:
  branches: [main] # run whenever you push to main
 workflow_dispatch: # plus a manual Run-workflow button

jobs:
 build_and_deploy:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v4

   - name: Set up Flutter
     uses: subosito/flutter-action@v2 # official wrapper
     with:
      channel: "stable"

   - run: flutter pub get
   - run: flutter build web --release --base-href="/"

   - name: Deploy to GitHub Pages
     uses: peaceiris/actions-gh-pages@v4 # battle-tested deployer :contentReference[oaicite:0]{index=0}
     with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      publish_dir: ./build/web
